### PR TITLE
Various fixes that were broken in github version

### PR DESCRIPTION
**Pull request by stoduk**
Various things were broken in github version (and 2.2, maybe?) - most fundamentally the breakage that book parsing would not find occurrences correctly (it was finding a very large number for one entity, and none for the others).

I have *not* tested this on Windows, only OS X.  If you can test it, great, if not I'll test it under Virtual Box at some point.  Certainly wasn't testing before we release - would be enough to:
1) check that finding Kindle and copying files across still works (ie. both doesn't error and actually does something).
2) check that things "fail" correctly if no Kindle is found

### CODE REVIEW

**Comment by stoduk** [comment]
@szarroug3 just wanted to check you saw the note about testing (or lack of) on Windows. Are you able to try this out?

**Comment by szarroug3** [comment]
@stoduk Sorry, got distracted and forgot to mention that I did test on Windows 10. Still working properly. Good job! :)

**Comment by szarroug3** [comment]
@stoduk I tested the aliases issue with A Christmas Carol before and after your fix. I got the same results both ways -- it never gave me a lot of mentions for 1 character and none for the rest. Maybe I was missing something? Anyways, I like your way better. It's more complete.

**Comment by stoduk** [comment]
re. testing: excellent, glad it worked!  I think it should avoid a
performance issue too (if I understand os.walk, then the code would have
bailed early if it found it was looking at a Kindle, but if it didn't find
the Kindle magic files it would carry on walking the entire external drive).

re. breakage.  Odd that you don't see it!  To check - did you try with and
without the fix for issue #5?  I saw the breakage with any book (not just
Xmas Carol I saw it with originally), and on both Windows/OS X.

I think the problem is this behaviour (from aliases.setter):
>>> "".replace(", ", ",").split(",")
['']

That is - if Qt calls back with an empty string for an alias, it was being
converted to an array containing an empty string, rather than an empty
array as we'd want.  This empty string was then being used as an alias -
and so gave "\b \b" as a regex pattern, which matches every space character
between words (hence the very large number of occurrences), and these were
being attributed to whichever alias was the last to be handled (as it was
overwriting which term the alias was for in BookParser.__init__).

[this behaviour of split() is odd, perhaps with some good underlying
reason, in that string.split() without any specifier mentioned will remove
empty strings from the result (mentioned in the help text explicitly!), but
with a specifying it leaves an empty string in there (it doesn't say why it
doesn't remove the empty string in this case!).  ]

Cheers,
Anthony

**Comment by szarroug3** [comment]
I tried it with the 2.1.0 zip.. Maybe I introduced the issue after that
release.. Will try again at home

**Comment by szarroug3** [comment]
Ah! I was able to reproduce it!

**Comment by stoduk** [comment]
Great, glad you confirmed, always better to make sure a problem is
correctly understood - especially with unfamiliar code.

**Comment by szarroug3** [comment]
Yeah it only happened if you opened the book preferences before creating
the x-ray. That's why I couldn't reproduce it at first.

**Comment by stoduk** [comment]
I'm glad we kept talking about this, as I've found another instance of the
bug in a different path.  I've just submitted a new pull request, hopefully
obvious from the issue #13 details.

**Pull request merged**
